steps:
  - name: python
    entrypoint: bash
    args:
      - '-c'
      - |
        pip install --upgrade platformio
        pio run
    dir: .
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-firmwares/$TAG_NAME'
    paths:
      - /workspace/.pio/build/esp32/firmware.bin
